//USER
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_USERTYPE = 'SET_USERTYPE';
export const SET_TOKEN = 'SET_TOKEN';


//MERCHANT
export const SET_MERCHANT_PROFILE = 'SET_MERCHANT_PROFILE';
export const CLEAR_MERCHANT_PROFILE = 'CLEAR_MERCHANT_PROFILE';

export const SET_MERCHANT_LOCATION = 'SET_MERCHANT_LOCATION';

export const SET_MAP_LOCATION = 'SET_MAP_LOCATION';
export const CLEAR_MAP_LOCATION = 'CLEAR_MAP_LOCATION';

//DATA
export const SET_LAUNDRY_SHOPS = 'SET_LAUNDRY_SHOPS';
export const SET_LAUNDRY_SERVICES = 'SET_LAUNDRY_SERVICES';
export const SET_SELECTED_LAUNDRY_SERVICE = 'SET_SELECTED_LAUNDRY_SERVICE';

export const SET_LAUNDRY_CLOTH = 'SET_LAUNDRY_CLOTH';

//CUSTOMER
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA';
export const CLEAR_CUSTOMER_DATA = 'CLEAR_CUSTOMER_DATA';

export const SET_SELECTED_SHOP = 'SET_SELECTED_SHOP';

export const SET_CUSTOMER_ORDER = 'SET_CUSTOMER_ORDER';
export const CLEAR_CUSTOMER_ORDER = 'CLEAR_CUSTOMER_ORDER';

export const SET_CUSTOMER_BASKET = 'SET_CUSTOMER_BASKET';
export const CLEAR_CUSTOMER_BASKET = 'CLEAR_CUSTOMER_BASKET';

export const CLEAR_SELECTED_SHOP = 'CLEAR_SELECTED_SHOP';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

//UI
export const OPEN_ADD_CLOTHTYPE_MODAL = 'OPEN_ADD_CLOTHTYPE_MODAL';
export const OPEN_PRICING_MODAL = 'OPEN_PRICING_MODAL';
export const OPEN_SERVICE_PRICING_MODAL = 'OPEN_SERVICE_PRICING_MODAL';
export const OPEN_ADDONS_MODAL = 'OPEN_ADDONS_MODAL';
export const OPEN_CUSTOMER_ADDONS_MODAL = 'OPEN_CUSTOMER_ADDONS_MODAL';
export const OPEN_BASKET_MODAL = 'OPEN_BASKET_MODAL';
export const CLOSE_MODALS = 'CLOSE_MODALS';

//Message
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const CLEAR_CONVERSATIONS = 'CLEAR_CONVERSATIONS';
